### ISSUE TITLE
Effizientes Datenbankschema für schnellen Zugriff.

### ISSUE THREAD

**Issue by xItsDylan** [Antgenix1/CareMinderV2#13]
### Als Entwickler möchte ich sicherstellen, dass das Datenbankschema effizient organisiert ist, um einen schnellen Zugriff und eine einfache Speicherung der Daten zu gewährleisten.

**Akzeptanzkriterien**
- Das Datenbankschema ist gut strukturiert und optimiert. 
- Die Speicherung und der Abruf von Daten erfolgen effizient und ohne Verzögerungen. 
- Das Schema unterstützt alle Informationen aus den Anfragen.

**Comment by Antgenix1** [comment]
![Image](https://github.com/Antgenix1/CareMinderV2/assets/105075955/cc6b560b-0a96-4ab1-b116-a92e5a182cb4)
