### ISSUE TITLE
Frage per Sprachaufnahme erfassen

### ISSUE THREAD

**Issue by xItsDylan** [Antgenix1/CareMinderV2#4]
### Indem ich den «Tell me your questions»-Button als Patient auf der Patient Main Page auswähle, möchte ich eine Frage per Sprachaufnahme erfassen können.

**Akzeptanzkriterien**
•	Der Button «Tell me your questions» ist auf der Patient Main Page verfügbar.
•	Durch Auswahl des Buttons öffnet sich die Patient Recording Page.
•	Die Sprachaufnahme startet, wenn die Patient Recording Page geöffnet ist.

**Comment by Havilash** [comment]
Done
